meta_product_name: "Yellow-Ticket"
meta_title: "Yellow-Ticket - Share more, waste less"
meta_description: "Place to advertise close to expiry food items to reduce waste"
meta_image: "download-app.svg"
