meta_product_name: "Yellow-Ticket"
meta_title: "Yellow-Ticket - Share more, waste less"
meta_description: "A place to advertise close to expiry food items to reduce waste in the community"
meta_image: "food.jpg"
